verde="\033[0;32m"
negrita="\033[1m"
verde_negrita="\033[1;32m"
reset="\033[0m"

echo ""
echo "───────────────────────────────────────────────────────────────"
echo -e "${negrita}Bienvenido a Vendler${reset}"
echo -e "Asistente para la detección de aktionsart y formalización de"
echo -e "estructuras lógicas en RRG"
echo ""
echo "Versión 1.0 (2025)"
echo "Comentarios a: Carlos González Vergara (cgonzalv@uc.cl)"
echo ""
echo -e "${negrita}Escribe:${reset} ${verde_negrita}python main.py${reset} ${negrita}para ejecutar el programa${reset}"
echo "───────────────────────────────────────────────────────────────"
echo ""
