verde="\033[0;32m"
reset="\033[0m"

echo ""
echo "───────────────────────────────────────────────"
echo "Bienvenido a este asistente de análisis en RRG"
echo "Versión 1.0 (2025)"
echo "Comentarios a: Carlos González Vergara (cgonzalv@uc.cl)"
echo ""
echo -e "Escribe:  ${verde}python main.py${reset} para ejecutar el programa"
echo "───────────────────────────────────────────────"
echo ""
