verde="\033[0;32m"
reset="\033[0m"

echo ""
echo "───────────────────────────────────────────────"
echo "Bienvenido a Vendler"
echo "Asistente para la detección de aktionsart y formalización de"
echo "estructuras lógicas en RRG"
echo ""
echo "Versión 1.0 (2025)"
echo "Comentarios a: Carlos González Vergara (cgonzalv@uc.cl)"
echo ""
echo -e "Escribe:  ${verde}python main.py${reset} para ejecutar el programa"
echo "───────────────────────────────────────────────"
echo ""
